seed: 42 # seed used in all of the random seed generation purposes
n_sample: 1000 # default - used for synthetic dataset generation
n_class: 3 # default class - used for synthetic dataset generation
n_feature: 5 # for synthetic datasets
fold: 2 # kfold default
m1: 1 # polynomial degree
l_rate: 0.05
max_iteration: 500
reg_param_lambda: 0.00001
test_size: 0.2

dataset: ["synthetic", "iris", "digits"]
data_dir: &data_dir "data/"
file_patterns: ["train.csv", "test.csv"]

model:
  model_dir: "models/"
  training_model: &train_model "training_model.pkl"
  best_model: &live_model "best_model.pkl"
  
data_pipelines:
  requested_dataset: "iris"
  batch:
     source: "synthetic" # use some source csv if  needed inside data folder
     target_column: "label"
     output_path: *data_dir
     drift_threshold: 0.05 # if KL

mlflow: 
  tracking_uri: "https://localhost:54058"
  default_port: 54058
  experiment_name: "lr_iris_train_experiment"
  log_file: "mlruns/mlflow.log"

training:
  model_dir: "models/"
  training_model: "training_model.pkl"
  model_path: *train_model # reference to above model types
  test_size: 0.2
  retrain: true

deployment:
  best_model: "best_model.pkl"
  backup_model: *train_model
  model_path: *live_model # reference to model that is launched

# anchors and aliases
dvc:
  remote: "False"
  remote_storage: "s3://dvc_bucket/path"
  local_storage: "dvc_bucket/"
