name: Docker CI/CD deploy

on:
  push:
    branches: cicd-launch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # not to uncomment
      # Used in pre-build steps to ensure dependencies are ready
      # - name: Build the docker image (reading Dockerfile)-Docker daemon is not running yet.
      #   run: docker compose build 
  
      # used in deployment/testing to run the app
      - name: Launch service in docker-compose.yml, build if img doesnt exist, run until job exits.
        run: docker compose up