name: docker build/test/close 

on:
  push:
    branches:
      - cicd-prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker compose build

      - name: Run Tests
        run: make full_coverage

      - name: Stop Containers
        run: docker compose down
