name: CI/CD Pipeline

on:
  push:
    branches: cicd-prod
  workflow_dispatch:

jobs:
  local-github-push-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          script: |
            make all
  
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          script: |
            docker build -t lr:latest .
            
  
  docker-compose-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          script: |
            docker compose pull